config/routes.rb
Beebuzz::Application.routes.draw do
  root :to => "pages#home"

  match '/about' => 'pages#about', :as => :about
  match '/beebucks' => 'pages#beebucks', :as => :beebucks
  match '/contact' => 'pages#contact', :as => :contact
  match '/main' => 'pages#main', :as => :main
  match '/' => 'pages#home', :as => :home
  match '/languagepick' => 'pages#languagepick', :as => :languagepick
  match '/numbers1' => 'pages#numbers1', :as => :numbers1
  match '/numbers2' => 'pages#numbers2', :as => :numbers2
  match '/numbers3' => 'pages#numbers3', :as => :numbers3
  match '/privacy' => 'pages#privacy', :as => :privacy
  match '/profile' => 'pages#profile', :as => :profile
  match '/register' => 'pages#register', :as => :register
  match '/story1' => 'pages#story1', :as => :story1
  match '/story2' => 'pages#story2', :as => :story2
  match '/story3' => 'pages#story3', :as => :story3

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def privacy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beebuzz</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller.action_name %>">	

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="container">
	<div class="box sm">
		<%= image_tag "beebuzz__logo.png" %></br>
		Imagine being in class with your favorite teacher, and the class is held at your favorite amusement park. That's the environment that we're building at BeeBuzz. Parents play a key role in their children's education. We're going to help by providing them with all the tools possible to increase their interactions with their children.</br></br>
		Sign up here for the beta here:
		<form action ="">
			<input type="text_field">
			<input type="submit" value="submit">
		</form></br>
		Follow us on Twitter: <%= link_to "@beebuzz", "http://www.twitter.com/beebuzz" %></br>
		Read our blog: <%= link_to "BeeBuzz Blog", "http://beebuzzblog.tumblr.com" %></br>
		Email us: <%= link_to "Contact Us", contact_path %></br></br>

		<%= link_to "Wireframe", register_path %> - <%= link_to "About Us", about_path %>
	</div>
</div>

app/views/pages/languagepick.html.erb
<div>
  <%= link_to "Bienvenue, Erika !" %>
  <ul>
    <li><%= link_to "5 BeeBucks", beebucks_path %></li>
    <li><%= link_to "Your profile", profile_path %></li>
  </ul>
</div>

<div>
	<form action="main.html">
	Your languages
		<div>
			<label>Choose original language:</label>
			<div>
				<select name="language1">
					<option value="French">French</option>
					<option value="English">English</option>
					<option value="None">None</option>
				</select>
			</div>
		</div>
		
		<div>
			<label>Choose translation:</label>
			<div>
				<select name="language2">
					<option value="English">English</option>
					<option value="French">French</option>
					<option value="None">None</option>
				</select>
			</div>
		</div>
		
		<div>
			<input type="submit" value="Register">
		</div>
	</form>
</div>

<div>
	<p><h6>(For the purpose of this demo the languages will be French/English)</h6></p>
	<hr>
	<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
</div>

app/views/pages/main.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Your account", profile_path %>)
	</div>
	
	<div class="row">
		<div class="column">
			<h3>Lire une histoire (Read a story):</h3>
			<div class="block">
				<%= link_to "T'choupi va a la piscine (T'choupi goes to the pool)", story1_path %>
			</div>
			<div class="block">
				T'choupi s'habille tout seul (T'choupi gets dressed all by himself) - Bientot/Coming soon
			</div>
		</div>
		<div class="column">
			<h3>Apprendre des mots (Learn new words):</h3>
			<div class="block">
				<%= link_to "Les chiffres (Numbers)", numbers1_path %>
			</div>
			<div class="block">
				Les lettres (Letters) - Bientot/Coming soon
			</div>
		</div>
		<div class="column">
			<h3>Ecouter une contine (Listen to a lullaby):</h3>
			<div class="block">
				Frere Jacques (Brother Jacques)
			</div>
			<div class="block">
				Twinkle twinkle Little Star - Bientot/Coming soon
			</div>
		</div>
	</div>

	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>

app/views/pages/numbers1.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Back", main_path %>)
	</div>
	
	<div class="box">
		Un !
	</div>
	
	<div class="box sm">
		<h2>1</h2>
	</div>
	<div class="box">
		<p class="book-nav"><%= link_to "Previous page", main_path, :class => "previous" %> One! <%= link_to "Next page", numbers2_path, :class => "next" %></p>
	</div>
	
	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>

app/views/pages/numbers2.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Back", main_path %>)
	</div>
	
	<div class="box">
		Deux !
	</div>
	
	<div class="box sm">
		<h2>2</h2>
	</div>
	<div class="box">
		<p class="book-nav"><%= link_to "Previous page", numbers1_path, :class => "previous" %> Two! <%= link_to "Next page", numbers3_path, :class => "next" %></p>
	</div>
	
	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>

app/views/pages/numbers3.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Back", main_path %>)
	</div>
	
	<div class="box">
		Trois !
	</div>
	
	<div class="box sm">
		<h2>3</h2>
	</div>
	<div class="box">
		<p class="book-nav"><%= link_to "Previous page", numbers3_path, :class => "previous" %> Three! <%= link_to "Next page", main_path, :class => "next" %></p>
	</div>
	
	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/profile.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Back", main_path %>)
	</div>
	
	<div class="box sm">
		<h3>Update your profile:</h3>
		<form action="">
			Name : <input type="text" name="name" value="Erika"><br>
			Email: <input type=text name="email" value="Bahnik"><br>
			Email: <input type=text name="email" value="Christian"><br>
			<input type="submit" value="Update">
		</form>
		<h3>Update your password:</h3>
		<form action="">
			Password: <input type="password" name="password"><br>
			Confirm Password: <input type="password" name="password"><br>
			<input type="submit" value="Update Password">
		</form>
	</div>
	
	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>

app/views/pages/register.html.erb
<div class="container">
	<div class="box sm">
		<%= image_tag "beebuzz__logo.png" %>
	
		<form action="main.html">
			Register or log in:
			<div>
				<label>Email :</label>
					<input type="text" name="name"><br>
			</div>
			<div>
				<label>Password :</label>
					<input type="password" name="name"><br>
			</div>
			<div>
				<input type="submit" value="Log in">
			</div>
		</form>
		<div>
			<%= link_to "Contact Us", contact_path %> - <%= link_to "About Us", about_path %> - <%= link_to "BeeBuzz Blog", "http://beebuzzblog.tumblr.com" %>
		</div>
	</div>
</div>

app/views/pages/story1.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Back", main_path %>)
	</div>
	
	<div class="box">
		T'choupi enfile ses brassards et hop ! il va dans l'eau.</br>
		- Papi, regarde comme je nage vite !</br>
		- Bravo ! Essaie sans la planche  maintenant . . .
	</div>
	
	<div class="box sm">
		<%= image_tag "IMG_0005.jpg" %>
	</div>
	<div class="box">
		<p class="book-nav"><%= link_to "Previous page", main_path, :class => "previous" %> T'choupi puts on his buoys et jumps in the water!</br>
		- Grandpa, look how fast I can swim !</br>
		- Very nice ! Try without the plank now . . . <%= link_to "Next page", story2_path, :class => "next" %></p>
	</div>
	
	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>

	<img src="IMG_0005.jpg"></br>
	
	<h3></h3></br>
	
	<h6><%= link_to "Next page", story2_path %></h6>
</div>

app/views/pages/story2.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Back", main_path %>)
	</div>
	
	<div class="box">
		T'choupi se laisse glisser sur le toboggan . . . et plouf !</br>
		il atterrit dans les bras de papi.</br>
		- Youpi!
	</div>
	
	<div class="box sm">
		<%= image_tag "IMG_0008.jpg" %>
	</div>
	<div class="box">
		<p class="book-nav"><%= link_to "Previous page", story1_path, :class => "previous" %>T'choupi slides on the slide . . . and plouf !</br>
		he lands in Grandpa's arms.</br>
		- Woohoo!<%= link_to "Next page", story3_path, :class => "next" %></p>
	</div>
	
	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>

app/views/pages/story3.html.erb
<div class="container">
	<div class="box">
		Bienvenue Erika ! - You have <%= link_to "5 BeeBucks", beebucks_path %> (<%= link_to "Back", main_path %>)
	</div>
	
	<div class="box">
		- Allez, mon T'choupi,</br>
		on va rentrer, maintenant. </br>
		Tu trembles de froid . . .</br>
		- Nooon, paaaapi, caaa vaaa !
	</div>
	
	<div class="box sm">
		<%= image_tag "IMG_0009.jpg" %>
	</div>
	<div class="box">
		<p class="book-nav"><%= link_to "Previous page", story2_path, :class => "previous" %>
			- C'mon, my T'choupi,</br>
		we're going home now. </br>
		You're so cold you're shivering . . .</br>
		- Nooo, Graaaandpaaa, I'mmmm oookkkk !</br>
		- Woohoo!<%= link_to "Next page", main_path, :class => "next" %></p>
	</div>
	
	<div class="box">
		<%= link_to "About Us", about_path %> - <%= link_to "Contact us", contact_path %> - <%= link_to "BeeBuzz Blog", "http://jeanbahnik.com" %>
	</div>
</div>